[user]
name = "Herman J. Radtke III"
email = "herman@hermanradtke.com"

[ui]
default-command = "log"

[aliases]
# use difftastic
difft = ["diff", "--tool", "difft"]
# print first line of current revision
fl = ["log", "--no-graph", "-r", "@", "--template", "description.first_line()"]
# move ancestor bookmark to current revision
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
